### ISSUE TITLE
解压缩带目录的zip文件有bug

### ISSUE THREAD

**Issue by Wuvist** [meoow/unzipgbk#1]
貌似不会自动建立目录，以致写文件的时候报 no such file or directory
bug重现文件：http://pan.baidu.com/s/1hqgOs1Q#path=%252F%25E4%25BA%25A7%25E5%2593%2581%25E7%25BB%258F%25E7%2590%2586%25E4%25B9%25A6%25E7%25B1%258D

产品经理.zip

**Comment by meoow** [comment]
@Wuvist It should create the directories hierarchically, but I'll take a look at it.

**Comment by meoow** [comment]
@Wuvist The issue has been fixed, it's due to non-standardized zip archives of which files in sub-directories have no correspondingly preceding directory entries in them.
